<a href="https://colab.research.google.com/github/FGalvao77/Entendendo-por-tras-dos-panos-o-funcionamento-de-uma-Rede-Neural-Artificial/blob/main/Entendendo_por_%22tra%C5%9B_dos_panos%22_o_funcionamento_de_um_RNA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<br>

## **Entendendo _"por trás dos panos"_ o funcionamento de uma `Rede Neural Artificial`**
---
---

In [1]:
# instanciando uma lista com dados de entrada
inp = [1, 2, 3]

# visualizando o tipo do objeto e o seu conteúdo
type(inp), inp

(list, [1, 2, 3])

In [2]:
# acessando os elementos da lista através dos seus índices
inp[0], inp[1], inp[2]  

(1, 2, 3)

In [3]:
# instanciando uma lista com valores dos pesos
weight = [0.2, 0.8, -0.5]

# visualizando o tipo do objeto e o seu conteúdo
type(weight), weight

(list, [0.2, 0.8, -0.5])

In [4]:
# acessando os elementos da lista através dos seus índices
weight[0], weight[1], weight[2]

(0.2, 0.8, -0.5)

In [5]:
# instanciando o valor do viés (bias em inglês)
bias = 2

In [6]:
# operação do produto escalar de cada valor de entrada com o valor de viés
# e por fim, a somatória dos resultados
out = (
    (inp[0] * weight[0]) + (inp[1] * weight[1]) + (inp[2] * weight[2]) + bias
)

# visualizando o resultado final
out

2.3

In [7]:
# criando uma função para realizar o produto escalar dos dados
def nn(in_1: eval, in_2: eval, in_3: eval, 
       w_1: eval, w_2: eval, w_3: eval, 
       bias: eval) -> float:
    
    return ((in_1 * w_1) + (in_2 * w_2) + (in_3 * w_3)) + bias

In [8]:
# utilizando a função acima com dados de entrada, peso e viés
nn(1, 2, 3, 0.2, 0.8, -0.5, 2)

2.3

In [9]:
# importando o módulo para criar uma função mais estruturada para cálculo do produto escalar
from typing import List

# produto escalar de dois vetores e com um valor de viés
def dot_product(xs: List[float], ys: List[float], bias: float) -> float:
    return sum(x * y for x, y in zip(xs, ys)) + bias

In [10]:
# utilizando os mesmos dados de entrada, pesos e viés já utilizados anteriormente
dot_product(xs=[1, 2, 3], ys=[0.2, 0.8, -0.5], bias=2)

2.3

In [11]:
# instanciando novos dados de entrada, pesos e viés
inp_ = [1, 2, 3, 2.5]

w_1 = [0.2, 0.8 , -0.5, 1]
w_2 = [0.5, -0.91, 0.26, -0.5]
w_3 = [-0.26, -0.27, 0.17, 0.87]

bias_1 = 2
bias_2 = 3
bias_3 = 0.5

In [12]:
# realizando o produto escalar com os novos dados acima
outs = {
    'neuron_1': [(inp_[0] * w_1[0]) + (inp_[1] * w_1[1]) + (inp_[2] * w_1[2]) + (inp_[3] * w_1[3]) + bias_1],
    'neuron_2': [(inp_[0] * w_2[0]) + (inp_[1] * w_2[1]) + (inp_[2] * w_2[2]) + (inp_[3] * w_2[3]) + bias_2],
    'neuron_3': [(inp_[0] * w_3[0]) + (inp_[1] * w_3[1]) + (inp_[2] * w_3[2]) + (inp_[3] * w_3[3]) + bias_3]
}

# visualizando o resultado
outs

{'neuron_1': [4.8], 'neuron_2': [1.21], 'neuron_3': [2.385]}

In [13]:
# visualizando o resultado individualmente em cada neurônio
outs['neuron_1'], outs['neuron_2'], outs['neuron_3']

([4.8], [1.21], [2.385])

In [14]:
# instanciando cada resultado dos neurônios em objetos distintos
v1, v2, v3 = outs['neuron_1'], outs['neuron_2'], outs['neuron_3']

In [15]:
# visualizando o resultado em cada objeto
v1, v2, v3

([4.8], [1.21], [2.385])

In [16]:
# visualizando o tipo do objeto e seu conteúdo
type(v1), v1

(list, [4.8])

In [17]:
# concatenando e exibindo os resultados
outs['neuron_1'] + outs['neuron_2'] + outs['neuron_3']

[4.8, 1.21, 2.385]

In [18]:
# utilizando a função para calcular o produto escalar e imprimindo os resultados
print(dot_product(xs=inp_, ys=w_1, bias=bias_1),
      dot_product(xs=inp_, ys=w_2, bias=bias_2),
      dot_product(xs=inp_, ys=w_3, bias=bias_3), sep=' | ')

4.8 | 1.21 | 2.385


In [19]:
# importando e visualizando a versão da biblioteca
import numpy as np  # recursos matemáticos

print(f'[VERSION] NumPy: {np.__version__}')

[VERSION] NumPy: 1.22.4


In [20]:
# criando um objeto do tipo matriz - dados
data = np.array([
    [0, 0, 1],
    [1, 1, 1],
    [1, 0, 1],
    [0, 1, 1],
])

# tipo do objeto, sua dimensão e o seu conteúdo
type(data), data.ndim, data

(numpy.ndarray,
 2,
 array([[0, 0, 1],
        [1, 1, 1],
        [1, 0, 1],
        [0, 1, 1]]))

In [21]:
# criando um objeto do tipo matriz - rótulos
labels = np.array([
    [0, 1, 1, 0]
])

# tipo do objeto, sua dimensão e o seu conteúdo
type(labels), labels.ndim, labels

(numpy.ndarray, 2, array([[0, 1, 1, 0]]))

In [22]:
# realizando a transposição da matriz de rótulos com a função "transpose()"
labels.transpose()  # uma coluna com n_linhas

array([[0],
       [1],
       [1],
       [0]])

In [23]:
# também podemos realizar a redimensão da matriz com a função ".reshape(-1, 1)"
labels.reshape(-1, 1)

array([[0],
       [1],
       [1],
       [0]])

In [24]:
# instanciando novamente a matriz de rótulos e já realizando sua transposição
labels = np.array([
    [0, 1, 1, 0]
]).transpose()

# visualizando o conteúdo da matriz
labels

array([[0],
       [1],
       [1],
       [0]])

In [25]:
# podemos também transformar a matriz em n_colunas e uma linha
labels.T

array([[0, 1, 1, 0]])

In [26]:
# instanciando a matriz de rótulos
labels = np.array([
    [0, 1, 1, 0]
]).reshape(-1, 1)

labels

array([[0],
       [1],
       [1],
       [0]])

In [27]:
# redimensionando a matriz
labels.reshape(-1, )

array([0, 1, 1, 0])

In [28]:
# visualizando a matriz de rótulos
labels

array([[0],
       [1],
       [1],
       [0]])

In [29]:
# instanciando a semente aleatória
np.random.seed(1)

In [30]:
# definindo o peso da rede
w = 2 * np.random.random((3, 1)) - 1

# tipo do objeto, dimensão e o conteúdo
type(w), w.shape, w

(numpy.ndarray,
 (3, 1),
 array([[-0.16595599],
        [ 0.44064899],
        [-0.99977125]]))

In [31]:
# funação para calcular a sigmóide 
def sigmoid(x: float) -> float:
    return 1 / (1 + np.exp(-x))

In [32]:
# função para calcular a derivada da sigmóide
def derivative_sigmoid(x: float) -> float:
    return x * (1 - x)

In [33]:
# realizando um laço de repetição com os dados 
for i in range(1_000):
    input_layer = data
    output = sigmoid(x=np.dot(input_layer, w)).round(1)
    error = labels - output
    adjustments = error * derivative_sigmoid(x=output)
    w += np.dot(a=input_layer.T, b=adjustments)

# visualizando o resultado da rede
output

array([[0.],
       [1.],
       [1.],
       [0.]])

In [34]:
# instanciando uma nova matriz com novos dados
data_2 = np.array([
    [0, 0, 1],
    [1, 1, 1],
    [1, 0, 1],
    [0, 1, 1],
    [0, 0, 0],
    [1, 0, 0],
    [0, 1, 0]
])

# tipo do objeto e sua dimensão
type(data_2), data_2.ndim

(numpy.ndarray, 2)

In [35]:
# dimensão geral e o conteúdo da nova matriz
data_2.shape, data_2

((7, 3),
 array([[0, 0, 1],
        [1, 1, 1],
        [1, 0, 1],
        [0, 1, 1],
        [0, 0, 0],
        [1, 0, 0],
        [0, 1, 0]]))

In [36]:
# nova matriz com rótulos
labels_2 = np.array([
    [0, 1, 1, 0, 0, 1, 0]
]).reshape(-1, 1)

# tipo do objeto e sua dimensão
type(labels_2), labels_2.ndim

(numpy.ndarray, 2)

In [37]:
# dimensão geral e o conteúdo da nova matriz de rótulos
labels_2.shape, labels_2

((7, 1),
 array([[0],
        [1],
        [1],
        [0],
        [0],
        [1],
        [0]]))

In [38]:
# definindo o peso da rede
w = 2 * np.random.random((3, 1)) - 1

# tipo do objeto, dimensão e o conteúdo
type(w), w.shape, w

(numpy.ndarray,
 (3, 1),
 array([[-0.39533485],
        [-0.70648822],
        [-0.81532281]]))

In [39]:
# realizando o treinamento da rede com os novos dados e seus respectivos rótulos
for i in range(10_000):
    input_layer = data_2
    output = sigmoid(x=np.dot(a=input_layer, b=w)).round(1)
    error = labels_2 - output
    adjustments = error * derivative_sigmoid(x=output)
    w += np.dot(a=input_layer.T, b=adjustments)

# visualizando o resultado final da rede
output

array([[0. ],
       [1. ],
       [1. ],
       [0. ],
       [0.5],
       [1. ],
       [0. ]])

In [40]:
# instanciando outra matriz com novos dados
data_3 = np.array([
    [0, 0, 1, 0],
    [0, 0, 0, 1],
    [0, 1, 0, 1],
    [1, 0, 0, 0],
    [1, 0, 1, 0]
])

# tipo do objeto e sua dimensão
type(data_3), data_3.shape

(numpy.ndarray, (5, 4))

In [41]:
# nova matriz com rótulos
labels_3 = np.array([
    [1, 0, 0, 1, 1]
]).reshape(-1, 1)

# tipo do objeto e sua dimensão
type(labels_3), labels_3.shape

(numpy.ndarray, (5, 1))

In [42]:
# definindo o peso da rede
w = 2 * np.random.random((4, 1)) - 1

# tipo do objeto, dimensão e o conteúdo
type(w), w.shape, w

(numpy.ndarray,
 (4, 1),
 array([[-0.62747958],
        [-0.30887855],
        [-0.20646505],
        [ 0.07763347]]))

In [43]:
# realizando o treinamento da rede com os novos dados e seus respectivos rótulos
for i in range(10_000):
    input_layer = data_3
    output = sigmoid(x=np.dot(a=input_layer, b=w)).round(1)
    error = labels_3 - output
    adjustments = error * derivative_sigmoid(x=output)
    w += np.dot(a=input_layer.T, b=adjustments)

# visualizando o resultado final da rede
output

array([[1.],
       [0.],
       [0.],
       [1.],
       [1.]])

In [44]:
# importando módulo para criação de dataset
from sklearn.datasets import make_blobs

# definindo os atributos e os seus respectivos rótulos
features, labels = make_blobs(
    n_samples=20,
    centers=2,
    center_box=(-1, 1),
    cluster_std=0.1,
    random_state=np.random.seed(1)
)

In [45]:
# tipo do objeto e dimensão do objeto "features"
type(features), features.ndim

(numpy.ndarray, 2)

In [46]:
# dimensão geral e o conteúdo da matriz "features"
features.shape, features

((20, 2),
 array([[-1.06848852, -0.47985542],
        [-1.06689586, -0.39660131],
        [-0.07941523,  0.21049512],
        [-0.18319881,  0.35286315],
        [-0.27601791,  0.55512136],
        [-0.90961218, -0.34508542],
        [-1.01895481, -0.48409775],
        [-0.90968566, -0.46370764],
        [ 0.00852519,  0.3645283 ],
        [-1.01206027, -0.4889118 ],
        [-0.19819771,  0.40224355],
        [-0.0197452 ,  0.23463492],
        [-0.05257905,  0.33065986],
        [-1.06893733, -0.43501021],
        [-0.83379103, -0.32113044],
        [-0.16173462,  0.49893051],
        [-0.21877317,  0.33335212],
        [-0.13405208,  0.41571195],
        [-1.02656006, -0.34229931],
        [-1.11150229, -0.37189328]]))

In [47]:
# tipo do objeto e a dimensão da matriz "labels"
type(labels), labels.ndim

(numpy.ndarray, 1)

In [48]:
# realizando a transposição da matriz '"labels"
labels = labels.reshape(-1, 1)

# dimensão, dimensão geral e o conteúdo
labels.ndim, labels.shape, labels

(2,
 (20, 1),
 array([[1],
        [1],
        [0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [0],
        [1],
        [0],
        [0],
        [0],
        [1],
        [1],
        [0],
        [0],
        [0],
        [1],
        [1]]))

In [49]:
# instanciando o peso da rede
w = 2 * np.random.random((2, 1)) - 1

# tipo do objeto, dimensão geral e o conteúdo
type(w), w.shape, w

(numpy.ndarray,
 (2, 1),
 array([[-0.10403964],
        [ 0.78427174]]))

In [50]:
# realizando o treinamento da rede
for i in range(100_000):
    input_layer = features
    output = sigmoid(x=np.dot(a=input_layer, b=w)).round(1)
    error = labels - output
    adjustments = error * derivative_sigmoid(x=output)
    w += np.dot(a=input_layer.T, b=adjustments)

# visualizando o resultado
output

array([[1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.]])

In [51]:
# dimensão geral dos objetos
labels.shape, output.shape

((20, 1), (20, 1))

In [52]:
# dimensão dos objetos
labels.ndim, output.ndim

(2, 2)

In [53]:
# dados do "labels"
np.array(labels)

array([[1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1]])

In [54]:
# importando biblioteca para análise e manipulação de dados
import pandas as pd

# versão da biblioteca
print(f'[VERSION] Pandas: {pd.__version__}')

[VERSION] Pandas: 1.5.3


In [55]:
# concatenando os objetos
pd.concat(
    objs=[pd.DataFrame(labels.reshape(-1, )), 
          pd.DataFrame(output.reshape(-1, ))],
    axis=1, 
)

0    0
0   1  1.0
1   1  1.0
2   0  0.0
3   0  0.0
4   0  0.0
5   1  1.0
6   1  1.0
7   1  1.0
8   0  0.0
9   1  1.0
10  0  0.0
11  0  0.0
12  0  0.0
13  1  1.0
14  1  1.0
15  0  0.0
16  0  0.0
17  0  0.0
18  1  1.0
19  1  1.0

In [56]:
# instanciando um objeto do tipo data frame com os dados reais
df_real = pd.DataFrame(data=labels.reshape(-1, ), 
                       columns=['real'])

# visualizando o objeto criado
df_real

real
0      1
1      1
2      0
3      0
4      0
5      1
6      1
7      1
8      0
9      1
10     0
11     0
12     0
13     1
14     1
15     0
16     0
17     0
18     1
19     1

In [57]:
# instanciando um objeto do tipo data frame com os dados preditos
df_predict = pd.DataFrame(data=output.reshape(-1, ), 
                          columns=['predict'])

# visualizando o objeto
df_predict

predict
0       1.0
1       1.0
2       0.0
3       0.0
4       0.0
5       1.0
6       1.0
7       1.0
8       0.0
9       1.0
10      0.0
11      0.0
12      0.0
13      1.0
14      1.0
15      0.0
16      0.0
17      0.0
18      1.0
19      1.0

In [58]:
# concatenando os objetos "df_real" e "df_predict"
pd.concat(
    objs=[df_real, df_predict], axis=1
)

real  predict
0      1      1.0
1      1      1.0
2      0      0.0
3      0      0.0
4      0      0.0
5      1      1.0
6      1      1.0
7      1      1.0
8      0      0.0
9      1      1.0
10     0      0.0
11     0      0.0
12     0      0.0
13     1      1.0
14     1      1.0
15     0      0.0
16     0      0.0
17     0      0.0
18     1      1.0
19     1      1.0

In [59]:
%whos

Variable             Type                    Data/Info
------------------------------------------------------
List                 _SpecialGenericAlias    typing.List
adjustments          ndarray                 20x1: 20 elems, type `float64`, 160 bytes
bias                 int                     2
bias_1               int                     2
bias_2               int                     3
bias_3               float                   0.5
data                 ndarray                 4x3: 12 elems, type `int64`, 96 bytes
data_2               ndarray                 7x3: 21 elems, type `int64`, 168 bytes
data_3               ndarray                 5x4: 20 elems, type `int64`, 160 bytes
derivative_sigmoid   function                <function derivative_sigmoid at 0x7fc80f7c01f0>
df_predict           DataFrame                   predict\n0       1.0\<...>n18      1.0\n19      1.0
df_real              DataFrame                   real\n0      1\n1    <...>    0\n18     1\n19     1
dot_produc